agent:
  name: td3
  class: agent.td3.TD3Agent
  params:
    obs_dim: ??? # to be specified later
    action_dim: ??? # to be specified later
    action_range: ??? # to be specified later
    device: ${device}
    critic_cfg: ${double_q_critic}
    actor_cfg: ${squashed_actor}
    discount: 0.99
    actor_lr: 1e-4
    actor_betas: [0.9, 0.999]
    actor_update_frequency: 2
    critic_lr: 1e-4
    critic_betas: [0.9, 0.999]
    critic_tau: 0.005
    critic_target_update_frequency: 2
    target_policy_noise_std: 0.2
    target_policy_noise_clip: 0.5
    batch_size: 1024
    
double_q_critic:
  class: agent.critic.DoubleQCritic
  params:
    obs_dim: ${agent.params.obs_dim}
    action_dim: ${agent.params.action_dim}
    hidden_dim: 1024
    hidden_depth: 2
    
squashed_actor:
  class: agent.actor.SquashedActor
  params:
    obs_dim: ${agent.params.obs_dim}
    action_dim: ${agent.params.action_dim}
    hidden_depth: 2
    hidden_dim: 1024